### ISSUE TITLE
Calculation allows a value outside of my step

### ISSUE THREAD

**Issue by dynamicvisionsgis** [zhif7782/0525-holistic-testing#10]
**Describe the bug**
As a data management control, step value will be important to control the range of values that are acceptable, such as requiring all values to only allow decimals of 0.5 after an integer. If I use the calculate value and put in a value + 5.25, the calculation allows a value to be entered outside of my specified step range. In the example below, the calculation allows the value to be 10.25 but it should only be 10 or 10.5 according to the step parameter I have set.

**To Reproduce** See screenshots below of settings and result.
<img width="193" alt="image" src="https://github.com/zhif7782/0525-holistic-testing/assets/134633238/41506c72-f284-4d26-9862-b6a042578b18">
<img width="345" alt="image" src="https://github.com/zhif7782/0525-holistic-testing/assets/134633238/ea8ff9ab-b2f5-46ad-bce7-5d010926bf63">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 113.0.1774.50 (Official build) (64-bit)

**Comment by IsmaelInRedlands** [comment]
It seems to me like this behavior is acceptable.  One should not be able to enter a value outside of the range (-50 to +50 as shown in the screenshot below), but anything within the range should be acceptable.  This is how we have it in the mobile app too.
@zhif7782  what do you think?
@dynamicvisionsgis  Can you describe a specific use case where you think we should reject a value if it does not match the step?

**Comment by dynamicvisionsgis** [comment]
There have been positions I have held or situations I have been in within
scientific studies or data controlled environments where we were to always
round to the nearest half or whole number. In data science, I don't believe
this is an unreasonable situation, so that is what I thought the step
control was taking into consideration so that the data could be managed for
quality in those situations with not allowing entries other than what the
program requires.

That is all I know. I'm not a hard core advocate of either way you decide
to go, but I know there are use cases.

Thanks,
Kara E. Utter, MSES, BS
Dynamic Visions GIS
Portfolio: https://geoidinthesky.wixsite.com/karautter
<http://geoidinthesky.wixsite.com/karautter>
Website: https://dynamicvisionsgis.com/my-work/
McCall, Idaho
208.315.4429

**Comment by IsmaelInRedlands** [comment]
@dynamicvisionsgis   Thanks a lot for the details. This is useful.
For now, we are going to allow calculations to set any value within the range. 
We feel enforcing the interval to be matched will cause issues in other workflows.
Ideally, the author will configure a calculation with rounding according to their specs.
