### ISSUE TITLE
Slider question selection uses the color of "Start color"

### ISSUE THREAD

**Issue by scottprindle** [zhif7782/0525-holistic-testing#11]
**Describe the bug**
Configuring a slider question with a start and end color (ex. start: red, end: green), if the "Selection color" is transparent (default), it does not show the color on the color ramp, but always uses the "Start color":

**To Reproduce**
1. Open Survey123 Web Designer (Beta). Add a Slider question type.
2. Configure a "Start color" (ex. FC9B9D) and an "End color" (ex. 96CF94)
3. The slider question shows a color ramp from red to green as expected, however moving the selection will place a point on the question as intended.
4. The selection point will inherit the "Start color", while it is expected to be "transparent" or inherit the color of the tick it is currently on.

**Expected behavior**

**Screenshots**
![image](https://github.com/zhif7782/0525-holistic-testing/assets/12354008/997d5b92-e064-4bdd-b36e-d68a18d0e575)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version 112.0.5615.140

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IsmaelInRedlands** [comment]
Thanks Scott. We are going to remove the selection color for now. We will think about this and figure out if we can bring the selection color in the future.
