### ISSUE TITLE
Slider - i18n decimal separator should honor user's language and region. Able to take comma/period

### ISSUE THREAD

**Issue by CeciliaSung** [zhif7782/0525-holistic-testing#12]
**Describe the bug**
Swedish locale decimal separator is comma. 
![image](https://github.com/zhif7782/0525-holistic-testing/assets/29442247/bc08e84d-af05-4e42-8ce4-ea64389085a7)

If I enter comma 1,5 at the start range, the value change it to 15,
![image](https://github.com/zhif7782/0525-holistic-testing/assets/29442247/e44d0502-3046-4003-85e3-63de1a91b8fa)

While use space as thousand separator, it return comma (US format). However, comma in some European countries means decimal separator.

![image](https://github.com/zhif7782/0525-holistic-testing/assets/29442247/f25c0c82-210a-4ab2-8c33-0c7126c5b088)

Attempted to enter 5.2 end up displaying 25 at the start and end range.
![image](https://github.com/zhif7782/0525-holistic-testing/assets/29442247/20b20562-4c17-45af-9f74-f1fe9b719f9a)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @CeciliaSung thanks for raising the issue. We plan to fix the issue in the next build.

**Comment by IsmaelInRedlands** [comment]
We will update the Beta website on June 7 to address this issue.
