### ISSUE TITLE
Dropdown edit Menu  problem in Spanish

### ISSUE THREAD

**Issue by LRazola** [zhif7782/0525-holistic-testing#13]
The edit menu does not look good in Spanish.

![image](https://github.com/zhif7782/0525-holistic-testing/assets/11696416/75db89c5-aebf-406a-bf4c-30bf32fe6eb3)

**Comment by oopsliu** [comment]
@LRazola Thanks for raising it. The translations will be available when it's released.

**Comment by oopsliu** [comment]
@LRazola We will update the Beta website with translations on June 7 to address this issue.
