### ISSUE TITLE
Missing Translation for Dynamic List from Layer for Dropdown menu

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#14]
**Describe the bug**
In this beta a UX for dynamic list is not yet translated:
![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/0e725a78-a4a3-45c1-8fa1-cf3e08de1164)

**To Reproduce**
1. Add DropDown menu layer
2. Set your AGO to Czech/Spanish....
3. Open the Dynamic list settings

**Expected behavior**
This dialog still waits for translation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Czech
 - Browser Opera
 - Version 98

**Comment by oopsliu** [comment]
@holubvl3 Thanks for raising it. The translations will be available when it's released.

**Comment by holubvl3** [comment]
Good to know, thank you @oopsliu.

**Comment by oopsliu** [comment]
@holubvl3 We will update the Beta website with translations on June 7 to address this issue.
