### ISSUE TITLE
List is not generating when I select on a map

### ISSUE THREAD

**Issue by wilkersonben89** [zhif7782/0525-holistic-testing#15]
**Describe the bug*
List of dropdown options from layer is not populating when I select a point on the map

![Snag_4dbbf807](https://github.com/zhif7782/0525-holistic-testing/assets/134632348/0ec9fcb3-98a6-4e65-b1d0-db544348abcd)

**Comment by IsmaelInRedlands** [comment]
Reviewed with Ben. All good. User Error. Closing.
