### ISSUE TITLE
The edit option to make list is not presenting the text correctly

### ISSUE THREAD

**Issue by claudiaalmeida79** [zhif7782/0525-holistic-testing#16]
**Describe the bug**

![image_2023-05-25_175931557](https://github.com/zhif7782/0525-holistic-testing/assets/134633075/c901eae5-635a-4f1c-b489-b9f74fcea990)

**To Reproduce**
1. Go to Add
2. Click on Pendente (in portuguese)
3. In Selection - Edit
4. From Layer
The text presented is not correct

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome]
 - Version 113.0.5672.127 (Compilação oficial) (64 bits)

**Comment by oopsliu** [comment]
@claudiaalmeida79 Thanks for raising it. The translations will be available when it's released.

**Comment by oopsliu** [comment]
@claudiaalmeida79 We will update the Beta website with translations on June 7 to address this issue.
