### ISSUE TITLE
Slider Bar - RTL issue

### ISSUE THREAD

**Issue by ediyacoo** [zhif7782/0525-holistic-testing#17]
**Describe the bug**
From Firas Ghandour

<img width="1296" alt="image" src="https://github.com/zhif7782/0525-holistic-testing/assets/3370342/39b8a2ef-8601-4512-9bdd-440c9ef587fe">

The start (e.g. 1) and end (e.g. 20) should be RTL.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IsmaelInRedlands** [comment]
This issue is not planned to be addressed, for consistency with the UX of sliders in the Map Viewer.
