### ISSUE TITLE
Dynamic list for dropdown menu does not show Desctription when list is based on domain field

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#19]
**Describe the bug**
The number - domain codes - are populated to the drop-down menu when the menu is based on field with a domain instead of domain descripotion

**To Reproduce**
1. Have a FL with a field with coded domain and some records inv - like I have in the field Výsledek kontroly

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/9793c3da-e234-40ee-9fa9-65109ea280f6)

3. Use this layer as a source fro Drop-down list
4. The list populates the codes of domain not values

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/e486eedd-0cc5-4ce4-abbb-786ea0fd7d6e)

**Expected behavior**
Please consider the drop-down menu support Domain description

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera
 - Version 89

**Comment by IsmaelInRedlands** [comment]
@zhif7782   Some additional info on this one: The ask is to be able to populate a list from a domain.  This is definitively out of scope for dynamic layers, but it is a fair request. For backlog.

Related to: https://github.com/zhif7782/0525-holistic-testing/issues/20

**Comment by oopsliu** [comment]
@holubvl3 Thanks for raising it; I have added it to our backlog.

**Comment by holubvl3** [comment]
Hello, I understand that loading the list from domain is a different question now, so please at least consider to display a value description in the list of features in the service from the list is populated. since if the field for a list will be a domain, which could happen often, it will be uneasy for users to use it.

Thank you,

**Comment by oopsliu** [comment]
@holubvl3 Displaying the label of the features instead of the codes will be available to test with the updated Beta website on June 7th.

**Comment by holubvl3** [comment]
Awesome! Thank you for info.

**Comment by holubvl3** [comment]
@oopsliu you, can close this. I´ve tested the domain - description in the drop-down list on Thursday and it worked for me. Thank you very much for fixing this!

**Comment by oopsliu** [comment]
Thanks @holubvl3 for the confirmation!
