### ISSUE TITLE
Make language dropdown list wider so the language labels can be read completely without having to use a tooltip

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#2]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/e3292bf1-2168-4731-97df-28cd362853c1)

**Describe the solution you'd like**
Make the dropdown wider so the labels fit.

**Describe alternatives you've considered**

**Additional context**

**Comment by fendiaoxiaoshuazi** [comment]
Hi @IsmaelInRedlands , discussed with the designer, we will make the dropdown wider enough to show the full content.
