### ISSUE TITLE
Support ctreate Drop-down menu list from Feature layer domain/list table

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#20]
**Is your feature request related to a problem? Please describe.**
Currently the Feature layer records is supported to create the list, but sometimes could be handy to create the list from the domain of the layer (when not all values of domain are used in the layer)

**Describe the solution you'd like**
I am seeking a way instead to load values from records in the FL, to populate the list from the domain of the field of the FL.

**Describe alternatives you've considered**

**Additional context**

**Comment by oopsliu** [comment]
@holubvl3 Thanks for raising it and I have added to our backlog.

**Comment by holubvl3** [comment]
Thank you @oopsliu!
