### ISSUE TITLE
Translation-search bar in Map question doesn't change in language

### ISSUE THREAD

**Issue by JENNYHUANG0227** [zhif7782/0525-holistic-testing#21]
**Describe the bug**
When we change the language, every part of the survey translated except for the search bar in map question 

**To Reproduce**
1. add a map question
2. add a translation language
4. change the survey language
5. the search bar isn't translated 

**Expected behavior**
granting a search bar translation field or a static multiple language setting  

**Screenshots**
![image](https://github.com/zhif7782/0525-holistic-testing/assets/134634130/80a4b657-2cbb-4a93-ae93-101a270b4fbf)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by fendiaoxiaoshuazi** [comment]
Hi @JENNYHUANG0227, the search bar text is a built-in string. In the web app, when you switch language, the search bar text should be displayed using the selected language.
