### ISSUE TITLE
Slider question - better handling of missing parameters

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#22]
**Is your feature request related to a problem? Please describe.**
when working with parameters of Slider question, the slider parameters does not behave like required fields - you can leave any of them empty and the you are not informed about that. 

The user gets the error on Preview, but the problem is that the error message itself is not translated, and this could be misleading to users since not all of them - those who work with Czech environment primarily - understand the English. On the other hand, translation of Error message is not a good idea, so please could you consider to add background color if those field are empty - to user realize - "Yes I should enter a value there"

**Describe the solution you'd like**
Highlight the background or disable Preview/Publish buttons, when the required values are not populated properly.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/0cb7542d-b0bb-402b-8fbe-765249791563)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3 , this for raising the issue, we plan to fix this issue in the next build.

**Comment by IsmaelInRedlands** [comment]
We will update the Beta website on June 7 to address this issue.

**Comment by holubvl3** [comment]
Awesome, thank you very much!
