### ISSUE TITLE
Missing Czech translation of Import/Export language menu

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#23]
**Describe the bug**
The Imoprt/Export translation is not yet translated to Czech

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/b4617ad4-2879-4fec-a43e-a604722bcf50)

**To Reproduce**
1. Set Survey123 to Czech
2. Open a survey and the import/export translation menu
3. See those untranslated strings

**Expected behavior**
It wait for Czech strings, so it should be translated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Czech
 - Browser Opera
 - Version 98

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3 , thanks for raising the issue, The pseudo strings will be replaced when the translation comes back.

**Comment by IsmaelInRedlands** [comment]
We will update the Beta website on June 7 to address this issue.

**Comment by holubvl3** [comment]
Thank you for confirmation! @fendiaoxiaoshuazi  @IsmaelInRedlands
