### ISSUE TITLE
Cannot unpack the translation ZIP file

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#24]
**Describe the bug**
I exported the ZIP file with Czech and English translation. But cannot unpcak it on Widows 11. Any idea what could be wrong? 

The ZIP file is here: 
[Nepojmenovaný průzkum_3_translation_1685037155552.zip](https://github.com/zhif7782/0525-holistic-testing/files/11567877/Nepojmenovany.pruzkum_3_translation_1685037155552.zip)

The Survey is here: https://survey123beta.arcgis.com/surveys/e4fcee606bd74f2a90e3a51d93fe8a84/design

**To Reproduce**
1. Go to Survey: https://survey123beta.arcgis.com/surveys/e4fcee606bd74f2a90e3a51d93fe8a84/design
2. Export the languages

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/7f367ba2-c81f-4a12-9d81-1a1aff8aaa85)

4. Try to open the ZIP 
5. I am getting error that Windows/7-zip is unable to open the zip. 

**Expected behavior**
It should work as in your demo - please could you test it on your side? 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Czech
 - Browser Opera
 - Version 98

**Smartphone (please complete the following information):**

**Comment by IsmaelInRedlands** [comment]
@holubvl3 Please email us at survey123@esri.com so we can have your email. We need access to your survey to reproduce.

**Comment by holubvl3** [comment]
Hi @IsmaelInRedlands, i found the trigger for this issue - the survey wasn´t published. When I published the survey to share it with you, it has started to work.

**Comment by IsmaelInRedlands** [comment]
@fendiaoxiaoshuazi  @zhif7782 @oopsliu  Good find by @holubvl3   Lets check if the export/import tools create an invalid zip file against a draft survey. If so, we may want to disable them (with a tooltip indicating that the tools are only available if the survey has been published), or handle exports from drafts.

**Comment by holubvl3** [comment]
Hi @IsmaelInRedlands @fendiaoxiaoshuazi @oopsliu, I was able to repro the issue. The issue has risen from the invalid Survey Design - from the testing of the slider. 

Steps to repro:

1) Create new Survey
2) Add the slider
3) Remove some value from the slider testing - for example step - keep the option empty
4) Add the second language to Survey
5) Export the ZIP and try to open - see the error.

See also the video - when the survey is ok - it works, when the setting is broken the error appears. 

https://github.com/zhif7782/0525-holistic-testing/assets/47881982/f94e5ca6-2c8e-4ec2-8eda-27d42e0f25b9

So this is quite special issue. Cannot say how many users will get to the same situation. It´s strange that translation is related to missing input value.

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3, thank you very much for the repro step, this is very helpful! We will update the Beta website on June 7 to address this issue.

**Comment by holubvl3** [comment]
Hi @fendiaoxiaoshuazi, looking forward to thursday testing.
