### ISSUE TITLE
Slider needs tick marks

### ISSUE THREAD

**Issue by wilkersonben89** [zhif7782/0525-holistic-testing#25]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to customize the labels for the tick marks between the start and end points. You could have the capability of labeling each one or at regular intervals. Not sure if it's possible to limit the number of interval labels if the distance between the start and end points is a large number (say 100 or 1000). 

I have seen similar functionality in ArcGIS Dashboards where graph tick marks are labeled.

![Snag_4e373393](https://github.com/zhif7782/0525-holistic-testing/assets/134632348/3c3ac863-74a0-4573-bdfd-787720d10a98)
![Snag_4e38aa16](https://github.com/zhif7782/0525-holistic-testing/assets/134632348/d0ab87fd-03af-485d-aac5-d118a1d2a9ad)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @wilkersonben89, thanks for the suggestion.

The enhancement is recorded in the internal dev issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/6389
