### ISSUE TITLE
Out-of-context Arabic characters and Edit choices pane is not fully localized

### ISSUE THREAD

**Issue by fghandour** [zhif7782/0525-holistic-testing#26]
**Describe the bug**
When editing a dropdown with a user whose profile is set to Arabic, some out-of-context Arabic words would appear in the Edit choices pane when the choices are generated from a layer. Moreover, it's noticed that the Edit choices pane is not fully localized in this case.

**To Reproduce**
1. Set the user's profile language to Arabic
2. Create a new survey in ArcGIS Survey123 beta and add a dropdown
3. Click on the drop down to start editing and configuring it
4. In the Edit pane, edit choices by clicking on 'Edit' besides 'Choices' (In Arabic, you'll click on 'تحرير')
5. In the Edit choices pane, click on 'From Layer'

**Expected behavior**
The Edit choices pane is not fully localized (Ex. From layer, Select choice label, Filter choices by, Location, Value). Moreover, out of context Arabic words and underscores appear before/ after the still-in-English labels (Ex. بيت, لاحقة)

**Screenshots**
![Arabic 2](https://github.com/zhif7782/0525-holistic-testing/assets/134787666/725271dd-5a52-45b3-9f91-3098cdb309b5)

**Desktop**
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version 113.0.5672.127

**Comment by fendiaoxiaoshuazi** [comment]
Hi @fghandour , thanks for raising the issue, The pseudo strings will be replaced when the translation comes back.

**Comment by IsmaelInRedlands** [comment]
@fghandour  We will update the Beta website on June 7 to address this issue.
