### ISSUE TITLE
Known issue: RTL Slightly misaligned numbers under Slider in Preview and Publish

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#28]
<div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;display:inline !important;">THIS IS A BUG FROM 3.18 BETA</span> </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Steps: </div><div style="box-sizing:border-box;">&nbsp;1. Prepare clean English Windows 11 with English Chrome </div><div style="box-sizing:border-box;">&nbsp;2. Load<span>&nbsp;</span><a href="https://survey123beta.arcgis.com/" style="box-sizing:border-box;text-decoration:underline;cursor:pointer;">https://survey123beta.arcgis.com</a>&nbsp;<span style="box-sizing:border-box;">and sign in (change AGOL language to target, for example AR)</span> </div><div style="box-sizing:border-box;">&nbsp;3. Create new survey - add Slider question </div><div style="box-sizing:border-box;">&nbsp;4.<span style="box-sizing:border-box;">&nbsp;Insert 1000 and 2000 as start and end value respectively</span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;">&nbsp;5. Save and either check Preview or Publish the survey and check in web form</span> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><br style="box-sizing:border-box;"></span> </div><div style="box-sizing:border-box;">Actual result: </div><div style="box-sizing:border-box;">Slightly misaligned numbers under Slider in Preview and Publish </div><div style="box-sizing:border-box;"><br> </div><div style="box-sizing:border-box;">Only in Preview and after Publish in web form; in Designer, there is no issue </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Expected result: </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><div style="box-sizing:border-box;">No misalignment </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div></span> </div><div style="box-sizing:border-box;">Additional info: </div><div style="box-sizing:border-box;">New feature in 3.18. Reproducible on all browsers, reproducible on both AR and HE. </div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;">Configuration used: </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;">English Windows 11 x64</span><br style="box-sizing:border-box;"> </div><div style="box-sizing:border-box;"><span style="box-sizing:border-box;">Arabic Chrome&nbsp;113.0.5672.127</span> </div><div style="box-sizing:border-box;"><a href="https://survey123beta.arcgis.com/" style="box-sizing:border-box;text-decoration:underline;cursor:pointer;">https://survey123beta.arcgis.com</a>&nbsp;build 3.18.19 </div><br> </div><br />

![aa](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/bd22b12e-ecbd-4ab9-8101-e97088cd3339)

<br/> Build Number : 3.18.19

**Comment by IsmaelInRedlands** [comment]
To be fixed in RC3

**Comment by fendiaoxiaoshuazi** [comment]
Fixed in RC3. Close the issue.
