### ISSUE TITLE
First Character on German Translation is missing on Drop Down Values Configuration 

### ISSUE THREAD

**Issue by trichtl** [zhif7782/0525-holistic-testing#29]
See also EAC-Post from today - 
When configure for a DropDown the Answers or layers - in German the first character is missing - to make it easier user Bearbeitung instead of Batchbearbeitung - so it saves space
see
https://earlyadopter.esri.com/project/forum/thread.html?cap=e69ef91f45744b98882c651f7b518eb7&forid={f93a6a79-f627-4727-8868-fc5e73406706}&topid={FCED4340-1371-4771-8092-CD1ACC1AA9A3}

**Comment by fendiaoxiaoshuazi** [comment]
Copied the screenshot from EAC:
<img width="431" alt="image" src="https://github.com/zhif7782/0525-holistic-testing/assets/26078106/a930f071-a07f-4520-8951-8d374f19e919">

**Comment by IsmaelInRedlands** [comment]
Thanks @trichtl 
We are going to work on this using two different approaches:

1. From a UX perspective, we will truncate the string properly adding ... at the end and also providing a tooltip with the full string
2. We will suggest to the localization team to use a shorter string so we do not have to truncate
