### ISSUE TITLE
Display informative success message after importing translation files

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#3]
**Is your feature request related to a problem? Please describe.**
After a successful import of a translation file, the Survey123 web designer does not provide any feedback. This can lead to confusion.  It is not clear what worked and what did not.

**Describe the solution you'd like**
Display an informative message indicating WHAT succeeded. For example, you can add a green toast message indicating that "French (fr)" and "French (fr-ch)" were imported successfully.

**Describe alternatives you've considered**

**Additional context**

**Comment by fendiaoxiaoshuazi** [comment]
Hi @IsmaelInRedlands, this will be improved in the RC2.
