### ISSUE TITLE
Better translation of "Choose from existing qustions"

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#30]
**Is your feature request related to a problem? Please describe.**
The idea is related to translation of the string. For drop-down menu where the last string is "Choose from existing questions" - in Czech = Vybrat z existující otázky (now here is: Choose from existing question -> not questions)

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/e1a5e11c-408f-4566-b876-0fe4c57cc39d)
Vybrat ze stávající otázky

**Describe the solution you'd like**
Better it would be: "Vyberte jednu z existujících otázek"

**Additional context**
It will be "smoother" to read the text.

**Comment by oopsliu** [comment]
Thanks @holubvl3. We will suggest to the localization team.

**Comment by akudinova477** [comment]
@oopsliu you can close this issue. I'm working with @holubvl3 directly on this

**Comment by holubvl3** [comment]
Hi @oopsliu, I will forward it to our localization manager. As @akudinova477 mentioned we can consider this as resolved. Thank you.

**Comment by oopsliu** [comment]
Thanks @holubvl3 @akudinova477
