### ISSUE TITLE
Choose from existing qustions - when nothing is choosen - highlight it in red or add and asterisk (in general add it to all required questions))

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#31]
**Is your feature request related to a problem? Please describe.**
Choosing the question here - it´s not clear for a first view that something should be chosen - that the question is required.

**Describe the solution you'd like**
Could you add the asterisk or some red highlight that this particular question is "required"? In general it´s not just about this question but all required items - like start/step/end for slider

**Additional context**
Improves the readability of survey settings.

**Comment by IsmaelInRedlands** [comment]
@zhif7782  See details in recording

44:20 Summary discussion usability. Suggestions:
    45:30-Change the label 'Select a question from the survey' with 'Select a location question from the survey'
    45:50- If there is only one location question in the survey, auto-select it
    46:00- Auto-scroll the scrollbar to reveal available questions in the list
    46:50- **Be more clear on parameters that are required**

**Comment by oopsliu** [comment]
@holubvl3 Thanks for the suggestion; we will have further discussions on how to improve the readability of the settings.

**Comment by holubvl3** [comment]
Great, thank you very much!
