### ISSUE TITLE
Fieldnames from Layer for Drop-List get into the Translation Export

### ISSUE THREAD

**Issue by trichtl** [zhif7782/0525-holistic-testing#32]
**Describe the bug**
Fieldnames from Layer for Drop-List get into the Translation Export

**To Reproduce**
Create a Drop down list with a Layer and a field
Export for Translation
You would see the fieldnames in the translation export
==> so you might start translate that as well
Would break the Survey, as those fieldnames, shouldn't be translateable

**Expected behavior**
Either exclude this from Export or ignore it on the import 

Found during 3.18 Holistic Testing on 08.06.2023
General problem - so no OS, ... Version is needed

**Comment by trichtl** [comment]
As Talked best would be not include it into Export for Translation

**Comment by fendiaoxiaoshuazi** [comment]
Thanks @trichtl, we will remove this in the upcoming July update.
