### ISSUE TITLE
Language - German-Austria is missing (maybe availible with June 2023 ArcGIS Online Release)

### ISSUE THREAD

**Issue by trichtl** [zhif7782/0525-holistic-testing#33]
**Describe the bug**
Language-Name German-Austria is missing

**To Reproduce**
Just choose the languages - there are for several languages several countries
With ArcGIS Online Release Jue 2023 on German language - German-Austria would be added

Not yet seen in the list - but maybe as we are not pointing to EAC ArcGIS Online, and it's maybe comming with the Release Next week.

Just to want to make sure, that this wouldn't be overseen

**Comment by akudinova477** [comment]
@trichtl as Survey123 3.18 release is planned before AGOL 2023.R02 release where German-Austria option will be introduced, Survey123 plans to pick up this option in their next release.

**Comment by IsmaelInRedlands** [comment]
@trichtl  German-Austria now available for testing in Beta. @akudinova477 

![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/32ba0cab-b0f0-49f3-a05b-e5fd1c38c1e9)
