### ISSUE TITLE
Redirect URL - disable users returning to the survey 

### ISSUE THREAD

**Issue by JENNYHUANG0227** [zhif7782/0525-holistic-testing#34]
**Is your feature request related to a problem? Please describe.**
Whenever the survey is redirected to a new website, we're still able to go back to the survey and resubmit it by hitting th "go-back" button on the browser. It'll be great if there's an option to disable user returning to the survey and avoiding repeated submission. 

**Describe the solution you'd like**responses. 
Create an option or a setting to stop user submit repeatedly on S123.

**Comment by IsmaelInRedlands** [comment]
@JENNYHUANG0227  I think this is already supported. Check the Collaborate tab option to limit responses to one:
![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/02378d2e-c7f5-45bc-8803-5ee03ae68e24)

What do you think? Can we close this issue?

**Comment by JENNYHUANG0227** [comment]
I didn't notice there's a feature for multiple submission. Yes, this is what I'm looking for and feel free to close the issue. Thanks!

**Comment by IsmaelInRedlands** [comment]
Thanks! @zhif7782   Ready to close
