### ISSUE TITLE
Void() url for URL redirect

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#36]
**Describe the bug**
I was testing the URL redirect on HTTP and then HTTPS page, but for the form instead of the URL set in the designer, present void() URL in the form.
![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/22edc814-6a4e-487b-95bc-e4fb02b0f554)

**To Reproduce**
1) Create new Survey on Beta site
2) Set URL redirect to http://www.arcdata.cz

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/9b3c7116-5a41-4cd7-bdf6-540e2ec8434d)

3) Publish the Survey and open it

4) See the URL link is void here. - manual and automatic redirect do open the empty survey page only

5) Edit the URL to HTTPS and prolong the redirect delay - re-publish and see the URL is still void.

**Expected behavior**
Propagate the URL to Form correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Czech
 - Browser Opera 
 - Version 99

**Comment by IsmaelInRedlands** [comment]
![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/7cb52e0a-c22f-435f-8824-b03029a732fa)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3, the here button in "Press here to cancel" is used to cancel the redirecting.  We will try to improve the string to make it more clear.

**Comment by holubvl3** [comment]
Hi Ruth @fendiaoxiaoshuazi - to click to "here" button was mentioned just for demonstration - in my case it works incorrectly for both use-cases - to wait or to click the "here" button.

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3, apologies for the confusion. I go through your comment again, and I think you mentioned 2 issues:
1. The auto-redirect set in the designer does not work. The feature should work properly now on production https://survey123.arcgis.com/. If possible, could you please try it again? Let me know if the issue still preserves.
2. The `here` link for reload/redirect shows `void()`. This is a be-designed behavior. `here` is a linked button that is used to:
   - Reload immediately
   - Cancel the redirection

**Comment by holubvl3** [comment]
Hi Ruth @fendiaoxiaoshuazi, thank you for clarification, all clear now. Redirects works! You can close this. Thank you!
