### ISSUE TITLE
Add Language option in web designer: Incorrectly defaults to previously selected language (Web Designer)

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#38]
**Describe the bug**
The Add Language dialog shows the previously added language by default as selected.

**To Reproduce**
1. Add a new language to your survey
2. Add another language to your survey. Note how the dialog will display the previously added language as selected. This should not be the case. It should appear unselected, because you do not want to add the same language twice.

![Designer 001](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/1bb8439f-7386-49f9-a5c4-1c151465e475)

**Expected behavior**
I expect no language to be selected, just like when I add a language for the first time.

**Comment by fendiaoxiaoshuazi** [comment]
Thanks @IsmaelInRedlands, nice catch! We will fix it in the next update.

**Comment by IsmaelInRedlands** [comment]
Fixed now in Beta
