### ISSUE TITLE
Auto translate not working for German-Switzerland (Web Designer)

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#39]
**Describe the bug**
Auto translate not working for German-Switzerland

**To Reproduce**
1. Add German Switzerland language to your survey
2. Use auto translate to translate. No translation will appear

**Expected behavior**
It should translate just like every other language

**Screenshots**

![002](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/f71af52b-128a-40f4-ac07-fa1b64c4ea4e)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @IsmaelInRedlands, I have reviewed all AGOL supported languages, and currently the following list cannot work properly
```
en-ca, en-gb, en-au (fallback to en-us)
fr-ch (fallback to fr-fr)
de-at, de-ch (fallback to de-de)
it-ch (fallback to it-it)
es-mx (fallback to es-es)
pt-br, pt-pt (API supports pt and pt-pt)
sr (API supports sr-Latn)
```
we will fix the issue in September BETA update.

**Comment by IsmaelInRedlands** [comment]
Nice! Thanks so much for thoroughly looking at this!

**Comment by IsmaelInRedlands** [comment]
Fixed in Beta now.
