### ISSUE TITLE
Inconsistent ISO code requirements in translation files

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#4]
**Describe the bug**
When creating translation files, I thought we were supposed to include in the header of the translation file the exact ISO code that matches the ISO code displayed in designer. For example for Spanish, the code is es-es as shown in the image below

![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/92030e14-b109-4a85-8137-1e8e8ffa6a5e)

However, when creating the language file, we need to specify es instead of es-es, as shown below. Otherwise, it does not work.

![image](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/8e244224-6d89-4c05-b9bd-ace3b98d3b1e)

For other locales, such as fr-ch, we need to specify fr-ch.  But for fr-fr, the ISO code that works is fr.  This is a bit confusing.

**To Reproduce**

**Expected behavior**
Please document differences or implement for consistency.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fendiaoxiaoshuazi** [comment]
Thanks @IsmaelInRedlands, we tried to fix this issue in the RC2.

Internal dev issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/6300
