### ISSUE TITLE
Machine translation does not work for Espanol-Mexico in S123 Designer

### ISSUE THREAD

**Issue by lhamel-1** [zhif7782/0525-holistic-testing#42]
**Describe the bug**
Machine translation does not work for Espanol-Mexico in S123 Designer

**To Reproduce**
1. Click on Languages > Add Language
2. Select "Espanol-Mexico" to add the language
3. Click on Languages > Auto translate > Select "Espanol-Mexico" > Translate
4. Does nothing. Translation still at 0%.

**Expected behavior**
That language should translate

**Screenshots**
![mx](https://github.com/zhif7782/0525-holistic-testing/assets/142329985/7913fbe6-a1d3-4d31-8663-f4906b8f430c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 115.0.5790.110

**Additional context**

**Comment by fendiaoxiaoshuazi** [comment]
Hi @lhamel-1 thanks for sharing, we will fix the issue in September BETA update.

**Comment by IsmaelInRedlands** [comment]
Now fixed in Beta @lhamel-1
