### ISSUE TITLE
Error received from S123 Assistant after clicking on "Generate". Error: list index out of range. Failed to parse survey json, please try again. 

### ISSUE THREAD

**Issue by lhamel-1** [zhif7782/0525-holistic-testing#44]
**Describe the bug**
Error received from S123 Assistant after clicking on "Generate". Error: list index out of range. Failed to parse survey json, please try again. 

**To Reproduce**
My prompts: 
- Create a survey to report hazardous trees in the city.
- Remove question 6
- Please make this survey available in English and French
- Generate survey draft
- Then, error occurs

**Expected behavior**
Should have generated survey draft. 

**Screenshots**
![translation](https://github.com/zhif7782/0525-holistic-testing/assets/142329985/1db2a7fd-b5fc-45f9-b547-fcdf3f17e323)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Version: 115.0.5790.110

**Comment by zhif7782** [comment]
Hi @lhamel-1 , thank you for sharing the feedback with us. I can reproduce this issue by following your prompts. We will fix it in a future update to the Survey123 assistant.
