### ISSUE TITLE
S123 Assistant did not generate survey in English and French as asked. 

### ISSUE THREAD

**Issue by lhamel-1** [zhif7782/0525-holistic-testing#45]
**Describe the bug**
S123 Assistant did not generate survey in English and French as asked. 

**To Reproduce**
My prompt: Demographic survey in English and French
In the conversation with the machine, the survey was in both languages. 
After clicking "Generate", the survey was only in English. All questions were only in English. No other language was added in the Language section.

Same behavior if do two separate prompts:
- Demographic survey 
- in English and French

**Expected behavior**
That the resulting survey would have the French language added in the Languages section 9since the machine did translate all the questions in the conversation). 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Version: 115.0.5790.110

**Comment by zhif7782** [comment]
Hi @lhamel-1 , although the model behind the Suvey123 assistant can output/translate survey design into multiple languages, the assistant itself currently does not support converting such a result into a real multilingual survey.

I've logged an enhancement issue in our dev repo and will fix it in a future update. Thank you for the feedback.
