### ISSUE TITLE
Empty list shows in Data tab on fields configured as Dynamic Lists

### ISSUE THREAD

**Issue by IsmaelInRedlands** [zhif7782/0525-holistic-testing#5]
**Describe the bug**
It is not possible to edit a value in the Data tab, if the question is configured with a dynamic list. See animation
![2023-05-25 Editing Dynamic List Value in Data Tab](https://github.com/zhif7782/0525-holistic-testing/assets/5918689/8b2c43ca-caa2-4a83-817e-20d900f3e901)

**To Reproduce**

**Expected behavior**
I think we should allow editing the value in the data tab. Either by allowing free text editing, or by populating the list following the same rules set for the dynamic list.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oopsliu** [comment]
Created a new issue in dev repo.
