### ISSUE TITLE
Slider Bar - negative step crashes the survey

### ISSUE THREAD

**Issue by craftywave** [zhif7782/0525-holistic-testing#6]
**Describe the bug**
When using a start value of 1 and an end value of 10, if the step value goes below 0 into negative numbers, the survey crashes and reloads to last save of the form.

**To Reproduce**
1. Go to Slider Range
2. Click on Start value of 1, End value of 10
3. Enter a negative Step value such as -3  
4. Form crashes and oops reload message appears to last saved version of the form

**Expected behavior**
If a negative value can't be used in this instance, a message indicating the value must be positive if there are no negative numbers in the start (for example).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @craftywave  thanks for raising the issue. We plan to fix this in the next build.

**Comment by fendiaoxiaoshuazi** [comment]
We will update the Beta website on June 7 to address this issue.
