### ISSUE TITLE
Minus Step in slider causes crash 

### ISSUE THREAD

**Issue by JENNYHUANG0227** [zhif7782/0525-holistic-testing#7]
**Describe the bug**
Whenever the step decreases to minus value, the web page freezes and crashes. After refresh the webpage, the setting of the slider is completely disappeared. 

**To Reproduce**
1. Go to 'Edit panel for the slider'
2. Click on 'Step'
3. Change the value to minus
4. See error and page crashed 

**Expected behavior**
Should constrain user enter a value that more then zero. 

**Screenshots**
![Untitled](https://github.com/zhif7782/0525-holistic-testing/assets/134634130/918cc39f-037c-427a-9ce1-4f38600401f2)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by IsmaelInRedlands** [comment]
@zhif7782

**Comment by fendiaoxiaoshuazi** [comment]
Hi @JENNYHUANG0227  thanks for raising the issue. We plan to fix this in the next build.

**Comment by fendiaoxiaoshuazi** [comment]
We will update the Beta website on June 7 to address this issue.
