### ISSUE TITLE
Problem with coma in Spain

### ISSUE THREAD

**Issue by LRazola** [zhif7782/0525-holistic-testing#8]
I can not use coma, only point for decimal in the beginning and the end.  I can use coma in the steps.

![image](https://github.com/zhif7782/0525-holistic-testing/assets/11696416/e4f6005c-2fd6-4283-ad32-eda5882d850e)

**Comment by fendiaoxiaoshuazi** [comment]
Hi @LRazola  thanks for raising the issue. We plan to fix this in the next build.

**Comment by fendiaoxiaoshuazi** [comment]
We will update the Beta website on June 7 to address this issue.
