### ISSUE TITLE
Comma decimal delimiter does not work properly for start/end/step value

### ISSUE THREAD

**Issue by holubvl3** [zhif7782/0525-holistic-testing#9]
**Describe the bug**
In the browser with Czech locale - comma decimal delimiter the comma is not considered properly as delimiter

It works fine of 0,2....0,6 but cannot enter value bigger than 1 with comma as decimal separator like 1,2 2,5, 10,8

**To Reproduce**
1) Go to Slider question
2) Go to range and set 0,5 for start it works:

![image](https://github.com/zhif7782/0525-holistic-testing/assets/47881982/fefb8f2b-27f6-4bb7-9046-0af787559293)

3. Repeat but try to enter the value 5,1 - it won´t work - it allows to write it down 15, or change the label to 0,5
4. Repeat it with Step or End parameter
5. The only values works there are like 5.1 - with dot

**Expected behavior**
I would expect to work with comma in every cases.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11, Czech
 - Browser Opera 
 - Version 98

**Additional context**

**Comment by fendiaoxiaoshuazi** [comment]
Hi @holubvl3 thanks for raising the issue. We plan to fix this in the next build.

**Comment by fendiaoxiaoshuazi** [comment]
We will update the Beta website on June 7 to address this issue.

**Comment by holubvl3** [comment]
Good to know. Please would it be possible to update the documentation with this as a known issue?
